package cli

import (
	"context"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/harakeishi/shtrace/internal/storage"
)

// Markers delimiting the shtrace-owned region of a user's rc file. Everything
// between them is regenerated on `enable` and deleted on `disable`; anything
// outside is never touched.
const (
	blockBegin = "# >>> shtrace auto-wrap >>>"
	blockEnd   = "# <<< shtrace auto-wrap <<<"
)

// envAutoWrapActive marks a process tree that auto-wrap has already entered.
// The guard is deliberately separate from SHTRACE_SESSION_ID: shell-init
// exports that in every terminal, so gating on it would make auto-wrap a no-op
// for exactly the users who enabled both. A pre-set session ID instead means
// "join that session", which the normal propagation path already handles.
const envAutoWrapActive = "SHTRACE_AUTOWRAP_ACTIVE"

// autoWrapShells are the shell names shimmed by `enable`. Interactive shells
// and non-shim POSIX shells (dash) are out of scope; see README.
var autoWrapShells = []string{"bash", "zsh", "sh"}

// autoWrapPaths collects every path enable/disable/doctor operate on, derived
// from HOME so tests can point it at a temp directory.
type autoWrapPaths struct {
	home     string
	root     string // ~/.shtrace
	shimDir  string // ~/.shtrace/shims
	bashEnv  string // ~/.shtrace/bashenv.sh
	bashrc   string // ~/.bashrc
	zshenv   string // ~/.zshenv
	selfPath string // absolute path of the running shtrace binary
}

func newAutoWrapPaths() (autoWrapPaths, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return autoWrapPaths{}, fmt.Errorf("resolve home directory: %w", err)
	}
	root := filepath.Join(home, ".shtrace")

	// A relative or unresolvable path would be baked into shims that run with
	// an unknown cwd, so fall back to the bare name and let PATH resolve it.
	self, err := os.Executable()
	if err != nil || strings.ContainsRune(self, '\x00') {
		self = "shtrace"
	}
	// Under `go test` os.Executable() is the test binary, which would make the
	// shim re-run the whole suite. Tests set this to a real shtrace build.
	if override := os.Getenv("SHTRACE_SELF_PATH"); override != "" {
		self = override
	}

	return autoWrapPaths{
		home:     home,
		root:     root,
		shimDir:  filepath.Join(root, "shims"),
		bashEnv:  filepath.Join(root, "bashenv.sh"),
		bashrc:   filepath.Join(home, ".bashrc"),
		zshenv:   filepath.Join(home, ".zshenv"),
		selfPath: self,
	}, nil
}

// injectBlock returns content with the shtrace block set to body, replacing an
// existing block if present and appending one otherwise.
func injectBlock(content, body string) string {
	block := blockBegin + "\n" + body + "\n" + blockEnd + "\n"

	if stripped, removed := removeBlock(content); removed {
		content = stripped
	}
	if content != "" && !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	return content + block
}

// removeBlock strips the shtrace block from content. The second return value
// reports whether a block was present.
func removeBlock(content string) (string, bool) {
	start := strings.Index(content, blockBegin)
	if start < 0 {
		return content, false
	}
	endIdx := strings.Index(content[start:], blockEnd)
	if endIdx < 0 {
		// Truncated block (hand-edited rc file): drop everything from the
		// begin marker on, since we cannot tell where the user's content
		// resumes.
		return content[:start], true
	}
	end := start + endIdx + len(blockEnd)
	if end < len(content) && content[end] == '\n' {
		end++
	}
	return content[:start] + content[end:], true
}

// resolveRealShell finds the absolute path of the genuine shell binary by
// walking pathEnv, skipping shimDir so an installed shim never resolves to
// itself. Falls back to /bin/<name> when nothing is found.
func resolveRealShell(name, pathEnv, shimDir string) string {
	shimAbs, err := filepath.Abs(shimDir)
	if err != nil {
		shimAbs = shimDir
	}
	for _, dir := range filepath.SplitList(pathEnv) {
		if dir == "" {
			continue
		}
		if abs, err := filepath.Abs(dir); err == nil && abs == shimAbs {
			continue
		}
		candidate := filepath.Join(dir, name)
		info, err := os.Stat(candidate)
		if err != nil || info.IsDir() || info.Mode().Perm()&0o111 == 0 {
			continue
		}
		return candidate
	}
	return "/bin/" + name
}

// shimScript builds the shim that replaces a shell on PATH. It wraps only
// non-interactive invocations that carry arguments, so `bash` at a prompt and
// nested calls inside an existing trace pass straight through.
func shimScript(shtracePath, realShell string) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by `shtrace enable`. Remove with `shtrace disable`.\n")
	b.WriteString("REAL=" + shellQuote(realShell) + "\n")
	b.WriteString("SHTRACE=" + shellQuote(shtracePath) + "\n\n")
	b.WriteString("# Auto-wrap already entered this process tree: never wrap twice.\n")
	b.WriteString("if [ -n \"${" + envAutoWrapActive + ":-}\" ]; then\n  exec \"$REAL\" \"$@\"\nfi\n\n")
	b.WriteString("# No arguments means an interactive shell; out of scope for v1.\n")
	b.WriteString("if [ \"$#\" -eq 0 ]; then\n  exec \"$REAL\" \"$@\"\nfi\n\n")
	b.WriteString("for arg in \"$@\"; do\n")
	b.WriteString("  if [ \"$arg\" = \"-i\" ]; then\n    exec \"$REAL\" \"$@\"\n  fi\n")
	b.WriteString("done\n\n")
	b.WriteString("export " + envAutoWrapActive + "=1\n")
	b.WriteString("exec \"$SHTRACE\" -- \"$REAL\" \"$@\"\n")
	return b.String()
}

// bashEnvScript re-execs a non-interactive bash under shtrace. BASH_ENV is
// sourced before `bash -c` runs its command, and BASH_EXECUTION_STRING is set
// only for `-c` invocations — so interactive shells and script files are
// naturally excluded without an explicit test for them. This is what catches
// agents that invoke bash by absolute path, bypassing the PATH shim.
func bashEnvScript(shtracePath, realBash string) string {
	var b strings.Builder
	b.WriteString("# Generated by `shtrace enable`. Remove with `shtrace disable`.\n")
	b.WriteString("if [ -z \"${" + envAutoWrapActive + ":-}\" ] && [ -n \"${BASH_EXECUTION_STRING:-}\" ]; then\n")
	b.WriteString("  export " + envAutoWrapActive + "=1\n")
	b.WriteString("  if shopt -q login_shell 2>/dev/null; then\n")
	b.WriteString("    exec " + shellQuote(shtracePath) + " -- " + shellQuote(realBash) + " -l -c \"$BASH_EXECUTION_STRING\"\n")
	b.WriteString("  else\n")
	b.WriteString("    exec " + shellQuote(shtracePath) + " -- " + shellQuote(realBash) + " -c \"$BASH_EXECUTION_STRING\"\n")
	b.WriteString("  fi\n")
	b.WriteString("fi\n")
	return b.String()
}

// zshenvBody is the zsh counterpart to bashEnvScript. ~/.zshenv is sourced for
// every zsh invocation including `zsh -c`, and ZSH_EXECUTION_STRING is set only
// for -c, giving the same "only wrap command strings" behaviour.
//
// PATH and BASH_ENV are set here too, not just in .bashrc: a zsh terminal never
// reads .bashrc, so without this an agent launched from zsh would get neither
// the shims nor absolute-path bash capture. They must precede the re-exec below,
// which replaces the process.
func zshenvBody(shtracePath, realZsh, shimDir, bashEnvPath string) string {
	var b strings.Builder
	b.WriteString("export PATH=" + shellQuote(shimDir) + ":\"$PATH\"\n")
	b.WriteString("export BASH_ENV=" + shellQuote(bashEnvPath) + "\n")
	b.WriteString("if [ -z \"${" + envAutoWrapActive + ":-}\" ] && [ -n \"${ZSH_EXECUTION_STRING:-}\" ]; then\n")
	b.WriteString("  export " + envAutoWrapActive + "=1\n")
	b.WriteString("  if [[ -o login ]]; then\n")
	b.WriteString("    exec " + shellQuote(shtracePath) + " -- " + shellQuote(realZsh) + " -l -c \"$ZSH_EXECUTION_STRING\"\n")
	b.WriteString("  else\n")
	b.WriteString("    exec " + shellQuote(shtracePath) + " -- " + shellQuote(realZsh) + " -c \"$ZSH_EXECUTION_STRING\"\n")
	b.WriteString("  fi\n")
	b.WriteString("fi\n")
	return b.String()
}

// bashrcBody puts the shim dir ahead of the real shells on PATH and arms
// BASH_ENV for the absolute-path case.
func bashrcBody(shimDir, bashEnvPath string) string {
	return "export PATH=" + shellQuote(shimDir) + ":\"$PATH\"\n" +
		"export BASH_ENV=" + shellQuote(bashEnvPath) + "\n"
}

// writeFileAtomic replaces path via a temp file + rename so a crash mid-write
// can never leave a user's rc file truncated.
//
// Symlinks are resolved first: dotfiles setups commonly link ~/.bashrc into a
// repo, and renaming onto the link itself would replace it with a regular file
// and detach it from the user's dotfiles.
func writeFileAtomic(path string, data []byte, perm os.FileMode) error {
	if resolved, err := filepath.EvalSymlinks(path); err == nil {
		path = resolved
	}
	dir := filepath.Dir(path)
	f, err := os.CreateTemp(dir, ".shtrace-tmp-*")
	if err != nil {
		return err
	}
	tmp := f.Name()
	defer func() {
		if tmp != "" {
			_ = os.Remove(tmp)
		}
	}()

	if _, err := f.Write(data); err != nil {
		_ = f.Close()
		return err
	}
	if err := f.Chmod(perm); err != nil {
		_ = f.Close()
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		return err
	}
	tmp = ""
	return nil
}

// rcFilePerm returns the mode to write path with: an existing file keeps its
// own, so a 0600 rc file is not widened to world-readable by enable.
func rcFilePerm(path string) os.FileMode {
	if info, err := os.Stat(path); err == nil {
		return info.Mode().Perm()
	}
	return 0o644
}

// updateBlockInFile rewrites path so its shtrace block matches body. A missing
// file is created; an unreadable one is an error.
func updateBlockInFile(path, body string) error {
	content := ""
	b, err := os.ReadFile(path)
	switch {
	case err == nil:
		content = string(b)
	case !os.IsNotExist(err):
		return err
	}
	return writeFileAtomic(path, []byte(injectBlock(content, body)), rcFilePerm(path))
}

// removeBlockFromFile strips the shtrace block from path. A missing file or a
// file without a block is not an error, keeping `disable` idempotent.
func removeBlockFromFile(path string) (bool, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("read %s: %w", path, err)
	}
	updated, removed := removeBlock(string(b))
	if !removed {
		return false, nil
	}
	if err := writeFileAtomic(path, []byte(updated), rcFilePerm(path)); err != nil {
		return false, fmt.Errorf("write %s: %w", path, err)
	}
	return true, nil
}

// fileHasBlock reports whether path currently carries the shtrace block.
func fileHasBlock(path string) bool {
	b, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.Contains(string(b), blockBegin)
}

func runEnable(_ context.Context, args []string, stdout, stderr io.Writer) int {
	if len(args) > 0 {
		_, _ = fmt.Fprintf(stderr, "shtrace: unknown enable argument %q\n", args[0])
		_, _ = fmt.Fprintln(stderr, "usage: shtrace enable")
		return 2
	}

	// enable touches several files; a failure partway through leaves some of
	// them written. There is no rollback, so point the user at the command
	// that cleans up whatever did land.
	fail := func(format string, a ...any) int {
		_, _ = fmt.Fprintf(stderr, "shtrace: "+format+"\n", a...)
		_, _ = fmt.Fprintln(stderr, "shtrace: auto-wrap may be partially applied; run `shtrace disable` to clean up")
		return 1
	}

	p, err := newAutoWrapPaths()
	if err != nil {
		_, _ = fmt.Fprintf(stderr, "shtrace: %v\n", err)
		return 1
	}
	if err := os.MkdirAll(p.shimDir, 0o755); err != nil {
		return fail("mkdir shim dir: %v", err)
	}

	pathEnv := os.Getenv("PATH")
	realShells := make(map[string]string, len(autoWrapShells))
	for _, name := range autoWrapShells {
		real := resolveRealShell(name, pathEnv, p.shimDir)
		realShells[name] = real
		shimPath := filepath.Join(p.shimDir, name)
		if err := writeFileAtomic(shimPath, []byte(shimScript(p.selfPath, real)), 0o755); err != nil {
			return fail("write shim %s: %v", name, err)
		}
	}

	if err := writeFileAtomic(p.bashEnv, []byte(bashEnvScript(p.selfPath, realShells["bash"])), 0o644); err != nil {
		return fail("write bashenv: %v", err)
	}
	if err := updateBlockInFile(p.bashrc, bashrcBody(p.shimDir, p.bashEnv)); err != nil {
		return fail("update .bashrc: %v", err)
	}
	if err := updateBlockInFile(p.zshenv, zshenvBody(p.selfPath, realShells["zsh"], p.shimDir, p.bashEnv)); err != nil {
		return fail("update .zshenv: %v", err)
	}

	_, _ = fmt.Fprintln(stdout, "shtrace auto-wrap enabled:")
	_, _ = fmt.Fprintf(stdout, "  shims:   %s (bash, zsh, sh)\n", p.shimDir)
	_, _ = fmt.Fprintf(stdout, "  bashenv: %s\n", p.bashEnv)
	_, _ = fmt.Fprintf(stdout, "  rc:      %s, %s\n", p.bashrc, p.zshenv)
	_, _ = fmt.Fprintln(stdout, "")
	_, _ = fmt.Fprintln(stdout, "Open a new shell (or restart your agent) for this to take effect.")
	_, _ = fmt.Fprintln(stdout, "Verify with:  shtrace doctor")
	_, _ = fmt.Fprintln(stdout, "Turn off with: shtrace disable")
	_, _ = fmt.Fprintln(stdout, "")
	_, _ = fmt.Fprintln(stdout, "Auto-wrap records every agent command, so the store grows quickly.")
	_, _ = fmt.Fprintln(stdout, "Run `shtrace gc` periodically to reclaim disk space.")
	return 0
}

func runDisable(_ context.Context, args []string, stdout, stderr io.Writer) int {
	if len(args) > 0 {
		_, _ = fmt.Fprintf(stderr, "shtrace: unknown disable argument %q\n", args[0])
		_, _ = fmt.Fprintln(stderr, "usage: shtrace disable")
		return 2
	}

	p, err := newAutoWrapPaths()
	if err != nil {
		_, _ = fmt.Fprintf(stderr, "shtrace: %v\n", err)
		return 1
	}

	changed := false
	for _, rc := range []string{p.bashrc, p.zshenv} {
		removed, err := removeBlockFromFile(rc)
		if err != nil {
			_, _ = fmt.Fprintf(stderr, "shtrace: %v\n", err)
			return 1
		}
		if removed {
			changed = true
			_, _ = fmt.Fprintf(stdout, "removed shtrace block from %s\n", rc)
		}
	}

	if err := os.RemoveAll(p.shimDir); err != nil {
		_, _ = fmt.Fprintf(stderr, "shtrace: remove shim dir: %v\n", err)
		return 1
	}
	if err := os.Remove(p.bashEnv); err != nil && !os.IsNotExist(err) {
		_, _ = fmt.Fprintf(stderr, "shtrace: remove bashenv: %v\n", err)
		return 1
	}

	if !changed {
		_, _ = fmt.Fprintln(stdout, "shtrace auto-wrap was not enabled; nothing to do")
		return 0
	}
	_, _ = fmt.Fprintln(stdout, "shtrace auto-wrap disabled. Open a new shell for this to take effect.")
	return 0
}

func runDoctor(ctx context.Context, args []string, stdout, stderr io.Writer) int {
	if len(args) > 0 {
		_, _ = fmt.Fprintf(stderr, "shtrace: unknown doctor argument %q\n", args[0])
		_, _ = fmt.Fprintln(stderr, "usage: shtrace doctor")
		return 2
	}

	p, err := newAutoWrapPaths()
	if err != nil {
		_, _ = fmt.Fprintf(stderr, "shtrace: %v\n", err)
		return 1
	}

	status := func(ok bool) string {
		if ok {
			return "OK"
		}
		return "NG"
	}

	_, _ = fmt.Fprintln(stdout, "shtrace doctor")

	shimDirExists := false
	if info, err := os.Stat(p.shimDir); err == nil && info.IsDir() {
		shimDirExists = true
	}
	_, _ = fmt.Fprintf(stdout, "  shim dir:     %s  %s\n", status(shimDirExists), p.shimDir)

	if shimDirExists {
		for _, name := range autoWrapShells {
			shimPath := filepath.Join(p.shimDir, name)
			info, err := os.Stat(shimPath)
			ok := err == nil && info.Mode().Perm()&0o111 != 0
			_, _ = fmt.Fprintf(stdout, "    shim %-5s  %s\n", name, status(ok))
		}
	}

	// The shim only wins if it precedes the real shells on PATH.
	onPath := false
	shimAbs, absErr := filepath.Abs(p.shimDir)
	if absErr != nil {
		shimAbs = p.shimDir
	}
	for _, dir := range filepath.SplitList(os.Getenv("PATH")) {
		if abs, err := filepath.Abs(dir); err == nil && abs == shimAbs {
			onPath = true
			break
		}
	}
	_, _ = fmt.Fprintf(stdout, "  PATH entry:   %s  (shim dir on PATH of this process)\n", status(onPath))

	bashrcOK := fileHasBlock(p.bashrc)
	zshenvOK := fileHasBlock(p.zshenv)
	_, _ = fmt.Fprintf(stdout, "  %s:      %s\n", filepath.Base(p.bashrc), status(bashrcOK))
	_, _ = fmt.Fprintf(stdout, "  %s:      %s\n", filepath.Base(p.zshenv), status(zshenvOK))

	bashEnvOK := false
	if _, err := os.Stat(p.bashEnv); err == nil {
		bashEnvOK = true
	}
	_, _ = fmt.Fprintf(stdout, "  bashenv.sh:   %s  %s\n", status(bashEnvOK), p.bashEnv)

	binOK := p.selfPath != "shtrace"
	if _, err := os.Stat(p.selfPath); err != nil {
		binOK = false
	}
	_, _ = fmt.Fprintf(stdout, "  shtrace bin:  %s  %s\n", status(binOK), p.selfPath)

	probeOK, probeDetail := probeShim(ctx, p)
	_, _ = fmt.Fprintf(stdout, "  probe:        %s  %s\n", status(probeOK), probeDetail)

	if !shimDirExists || !bashrcOK || !probeOK {
		_, _ = fmt.Fprintln(stdout, "")
		_, _ = fmt.Fprintln(stdout, "Run `shtrace enable` to set up auto-wrap, then open a new shell.")
	}
	return 0
}

// probeShim runs `bash -c true` through the installed shim and confirms a new
// session was recorded, catching a shim that is installed but not actually
// wrapping (bad path baked in, non-executable, PATH shadowed).
func probeShim(ctx context.Context, p autoWrapPaths) (bool, string) {
	shimPath := filepath.Join(p.shimDir, "bash")
	if info, err := os.Stat(shimPath); err != nil || info.Mode().Perm()&0o111 == 0 {
		return false, "bash shim not installed"
	}

	env := envMap()
	dataDir, err := storage.ResolveDataDir(env, runtime.GOOS)
	if err != nil {
		return false, fmt.Sprintf("resolve data dir: %v", err)
	}

	before := latestSessionID(ctx, dataDir)

	cmd := exec.CommandContext(ctx, shimPath, "-c", "true")
	// Probe in isolation: clearing the auto-wrap guard stops a doctor run that
	// is itself inside a wrapped shell from seeing a false pass-through, and
	// clearing the session ID forces a fresh session so the check below is a
	// real before/after comparison rather than a child span join.
	cmd.Env = append(os.Environ(), envAutoWrapActive+"=", "SHTRACE_SESSION_ID=")
	if out, err := cmd.CombinedOutput(); err != nil {
		return false, fmt.Sprintf("probe command failed: %v: %s", err, strings.TrimSpace(string(out)))
	}

	after := latestSessionID(ctx, dataDir)
	if after == "" || after == before {
		return false, "shim ran but no new session was recorded"
	}
	return true, "bash -c through shim recorded a new session"
}

// latestSessionID returns the ID of the newest stored session, or "" when the
// store is unavailable or empty. Comparing IDs rather than counting rows keeps
// the probe correct once the store grows past any list limit.
func latestSessionID(ctx context.Context, dataDir string) string {
	store, err := storage.Open(dataDir + "/sessions.db")
	if err != nil {
		return ""
	}
	defer func() { _ = store.Close() }()
	if err := store.Migrate(ctx); err != nil {
		return ""
	}
	sessions, err := store.ListSessions(ctx, 1, func(error) {})
	if err != nil || len(sessions) == 0 {
		return ""
	}
	return sessions[0].ID
}
